chore(deps-dev): Bump prettier from 2.6.1 to 2.6.2 (#214)
Bumps [prettier](https://github.com/prettier/prettier) from 2.6.1 to 2.6.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/prettier/prettier/releases">prettier's releases</a>.</em></p>
<blockquote>
<h2>2.6.2</h2>
<p>🔗 <a href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#262">Changelog</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md">prettier's changelog</a>.</em></p>
<blockquote>
<h1>2.6.2</h1>
<p><a href="https://github.com/prettier/prettier/compare/2.6.1...2.6.2">diff</a></p>
<h4>Fix LESS/SCSS format error (<a href="https://github-redirect.dependabot.com/prettier/prettier/pull/12536">#12536</a> by <a href="https://github.com/fisker"><code>@​fisker</code></a>)</h4>

<pre lang="less"><code>// Input
.background-gradient(@cut) {
    background: linear-gradient(
        to right,
        @white 0%,
        @white (@cut - 0.01%),
        @portal-background @cut,
        @portal-background 100%
    );
}
<p>// Prettier 2.6.1
TypeError: Cannot read properties of undefined (reading 'endOffset')</p>
<p>// Prettier 2.6.2
.background-gradient(<a href="https://github.com/cut"><code>@​cut</code></a>) {
background: linear-gradient(
to right,
<a href="https://github.com/white"><code>@​white</code></a> 0%,
<a href="https://github.com/white"><code>@​white</code></a> (<a href="https://github.com/cut"><code>@​cut</code></a> - 0.01%),
<a href="https://github.com/portal-background"><code>@​portal-background</code></a> <a href="https://github.com/cut"><code>@​cut</code></a>,
<a href="https://github.com/portal-background"><code>@​portal-background</code></a> 100%
);
}
</code></pre></p>
<h4>Update <code>meriyah</code> to fix several bugs (<a href="https://github-redirect.dependabot.com/prettier/prettier/pull/12567">#12567</a> by <a href="https://github.com/fisker"><code>@​fisker</code></a>, fixes in <a href="https://github.com/meriyah/meriyah/"><code>meriyah</code></a> by <a href="https://github.com/3cp"><code>@​3cp</code></a>)</h4>
<p>Fixes bugs when parsing following valid code:</p>
<pre lang="js"><code>foo(await bar());
</code></pre>
<pre lang="js"><code>const regex = /.*/ms;
</code></pre>
<pre lang="js"><code>const element = &lt;p&gt;{/w/.test(s)}&lt;/p&gt;;
</code></pre>

</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/prettier/prettier/commit/d6f82a024a1f0c4c7418a49a8334862286a63c17"><code>d6f82a0</code></a> Release 2.6.2</li>
<li><a href="https://github.com/prettier/prettier/commit/2bca9d65f4e200349a45765a1f3ee1da01456e40"><code>2bca9d6</code></a> Add new workflow to prevent updating <code>users.yml</code> (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/11784">#11784</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/378370a01e00db8da33e7fde030699ffda29730f"><code>378370a</code></a> Build(deps): Bump leven from 3.1.0 to 4.0.0 (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/11349">#11349</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/3c96a08176576e038d0088f3209a54642de77077"><code>3c96a08</code></a> Build(deps): Bump strip-ansi from 6.0.0 to 7.0.0 (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/10731">#10731</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/1bfb08f2895dd12c256f663b3f6c00ab0cc4ecde"><code>1bfb08f</code></a> Build(deps): Bump meriyah from 4.2.0 to 4.2.1 (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/12567">#12567</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/9400c893a3226cf19b03538cd6ae42a280cfddb1"><code>9400c89</code></a> Refactor: Add a wrapped <code>normalizeCliOptions</code> version for CLI usage (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/12573">#12573</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/5e3de4828d6a7ac0fdf94a82ba36a20d7c190b8d"><code>5e3de48</code></a> Build(deps): Bump escape-string-regexp from 4.0.0 to 5.0.0 (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/10725">#10725</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/5d73acc42d00c869fb4634167037ea79c027048b"><code>5d73acc</code></a> Build(deps-dev): Bump esbuild from 0.14.29 to 0.14.30 (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/12581">#12581</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/e2eac0cb8a33f051cb94d34cf6a0f73256ea4677"><code>e2eac0c</code></a> Move some bundle test code into <code>tests/</code> (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/12577">#12577</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/7d33ed54520486b43e70218a6e152e8d1fc477e5"><code>7d33ed5</code></a> Build(deps-dev): Bump eslint-plugin-unicorn from 41.0.1 to 42.0.0 (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/12580">#12580</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/prettier/prettier/compare/2.6.1...2.6.2">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=prettier&package-manager=npm_and_yarn&previous-version=2.6.1&new-version=2.6.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>