chore(deps-dev): Bump prettier from 2.8.2 to 2.8.3 (#748)
Bumps [prettier](https://github.com/prettier/prettier) from 2.8.2 to 2.8.3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/prettier/prettier/releases">prettier's releases</a>.</em></p>
<blockquote>
<h2>2.8.3</h2>
<p>Support Angular 15.1</p>
<p>🔗 <a href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#283">Changelog</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md">prettier's changelog</a>.</em></p>
<blockquote>
<h1>2.8.3</h1>
<p><a href="https://github.com/prettier/prettier/compare/2.8.2...2.8.3">diff</a></p>
<h4>Allow self-closing tags on custom elements (<a href="https://github-redirect.dependabot.com/prettier/prettier/pull/14170">#14170</a> by <a href="https://github.com/fisker"><code>@​fisker</code></a>)</h4>
<p>See <a href="https://github.com/angular/angular/releases/tag/15.1.0">Angular v15.1.0 release note</a> for details.</p>

<pre lang="html"><code>// Input
&lt;app-test/&gt;
<p>// Prettier 2.8.2
SyntaxError: Only void and foreign elements can be self closed &quot;app-test&quot; (1:1)
&gt; 1 | &lt;app-test/&gt;
| ^^^^^^^^^
2 |</p>
<p>// Prettier 2.8.3
&lt;app-test /&gt;
</code></pre></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/prettier/prettier/commit/c990e522ce81712e2e70527a6ce3d7a87b3f1114"><code>c990e52</code></a> Release 2.8.3</li>
<li><a href="https://github.com/prettier/prettier/commit/4ad9160891c7209118ce8bd11f8a0f4a23b41417"><code>4ad9160</code></a> Angular: allow self-closing tags on custom elements (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/14170">#14170</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/06ea1ac0d05a7b7d463bdbb0b662b22f3d340be0"><code>06ea1ac</code></a> Stricter node type check (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/14165">#14165</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/c1b976572c7512dfa7d7407706891f511883c0ad"><code>c1b9765</code></a> feat: add copy to clipboard in code blocks (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/14153">#14153</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/3ef82ae06b41574d9c45ab2506553bcc00afc019"><code>3ef82ae</code></a> Remove and ignore <code>.node-version</code> file (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/14143">#14143</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/a37ce0b8f6b211be0d3c156326acec56960fa3fc"><code>a37ce0b</code></a> Clean <code>changelog_unreleased</code> (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/14144">#14144</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/4cf4c2c5630b4579307073b41bf4ea994d633c5a"><code>4cf4c2c</code></a> Fix typo in CHANGELOG (<a href="https://github-redirect.dependabot.com/prettier/prettier/issues/14137">#14137</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/26b45e361f614abfbd20c396b6fd6226b091d625"><code>26b45e3</code></a> Git blame ignore 2.8.2</li>
<li><a href="https://github.com/prettier/prettier/commit/b9c3cd4c7016dfb1bb3539c5b3db15fdd54b9f6f"><code>b9c3cd4</code></a> Bump Prettier dependency to 2.8.2</li>
<li><a href="https://github.com/prettier/prettier/commit/dc187f19368899df497d6cb805753740e1d87bf8"><code>dc187f1</code></a> Update dependents count</li>
<li>See full diff in <a href="https://github.com/prettier/prettier/compare/2.8.2...2.8.3">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=prettier&package-manager=npm_and_yarn&previous-version=2.8.2&new-version=2.8.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>